select count(*) from name;
select count(*) from title;
select count(*) from nameProfession;
select count(*) from nameTitle;
select count(*) from titleGenre;
select count(*) from titleAka;
select count(*) from titleDirector;
select count(*) from titleWriter;
select count(*) from titleEpisode;
select count(*) from titlePrincipals;
select count(*) from titleRating;
exit;